nginx:
    build: ./images/nginx
    container_name: docker_nginx
    links:
        - php
        - mysql
        - redis
        - mongo
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./works:/var/www
        - ./volumes/nginx/sites:/etc/nginx/sites-enabled
        - ./volumes/nginx/logs:/var/log/nginx
        - ./volumes/nginx/includes:/etc/nginx/includes
    environment:
        TZ: Asia/Shanghai
    extra_hosts:
        - "pet.bileji.com:127.0.0.1"
        - "service.bileji.com:127.0.0.1"
    restart: always
php:
    build: ./images/php
    container_name: docker_php
    ports:
        - "9000:9000"
    volumes: 
        - ./works:/var/www
        - ./volumes/php/bin:/usr/local/bin
        - ./volumes/composer:/root/.composer
    environment:
        TZ: Asia/Shanghai
    restart: always
redis:
    build: ./images/redis
    container_name: docker_redis
    ports:
        - "6379:6379"
    volumes:
        - ./volumes/redis/data:/data
    environment:
        TZ: Asia/Shanghai
    restart: always
mysql:
    build: ./images/mysql
    container_name: docker_mysql
    ports:
        - "3306:3306"
    volumes:
        - ./volumes/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        TZ: Asia/Shanghai
    restart: always
mongo:
    image: frodenas/mongodb
    container_name: docker_mongo
    ports:
        - "27017:27017"
    environment:
        MONGODB_DBNAME: admin
        MONGODB_USERNAME: admin
        MONGODB_PASSWORD: 123456
        TZ: Asia/Shanghai
    volumes:
        - ./volumes/mongo:/data
# gitlab:
#     build: ./images/gitlab
#     container_name: gitlab
#     ports:
#         - "2022:20"
#         - "2080:80"
#         - "2443:443"
#     volumes:
#         - ./volumes/gitlab/logs:/var/log/gitlab
#         - ./volumes/gitlab/data:/var/opt/gitlab
#         - ./volumes/gitlab/config:/etc/gitlab
#     restart: always
